version: 2

sources:
  - name: raw_data
    description: "Raw data sources for NYC taxi rides"
    database: my-project123-486104
    schema: zoomcamp
    tables:
      - name: ext_yellow_tripdata
      - name: ext_green_tripdata